* Zadanie 1.
  Napisz własną polimorficzną procedurę i zademonstruj jej działanie
  na obiektach kilku różnych typów.
* Zadanie 2.
  Napisz polimorficzne procedury wykorzystujące tablice oraz wariadyczną arność
  procedur. Skorzystaj z przykładu z Zoo.
* Zadanie 3.
  Proszę zaprojektować hierarchię klas wykorzystującą klasy abstrakcyjne.
* Zadanie 4.
  Proszę napisać program, który tworzy kolekcję (ale nie tablicę) liczb typu Double i
  wyznacza medianę i średnią na tej kolekcji. Kolekcja ma być generyczna. Proszę
  wykorzystać klasy kolekcji z biblioteki standardowej języka Java.
  Hint: java.util.Set oraz java.util.List powinny być obsługiwane przez Państwa procedury.
* Zadanie 5.
  Proszę napisać dowolny interfejs generyczny w Javie wyposażony w domyślne metody.
* Zadanie 6.
  Proszę napisać dowolny typ wyliczeniowy wyposażony w nietrywialny konstruktor i jakieś metody.
* Zadanie 7. (dla chętnych)
  Posługując się kodami klasy IntArray (https://github.com/kongra/SAN/blob/master/2020%20letni%20(Spring)/JiPP-Maven/src/main/java/san/utils/IntArray.java)
  proszę zrealizować operator(y) reduce.
