* Zadanie 1. Proszę zrealizować co najmniej 3 klasy
  modelujące pewien wybrany przez Państwa fragment rzeczywistości.
  - Klasy powinny być ze sobą znaczeniowo (semantycznie) powiązane.
  - Proszę utworzyć kilka obiektów tych klas.

* Zadanie 2. Proszę zrealizować w Javie polimorfizm ad-hoc
   oparty o niejawną konwersję oraz oparty o przeciążanie. Na dowolnym
   wybranym przez siebie przykładzie.
* Zadanie 3. Dla wybranego urządzenia rzeczywistego:
** Zaprojektuj interfejs opisujący działanie tego urządzenia i jego komunikację ze światem zewnętrznym
** Zrealizuj ten interfejs w języku Java
** Utwórz klasę stanowiącą implementację powyższego interfejsu
** Zaprezentuj działanie tworząc obiekty powyższej klasy i aktywizując je wywołaniami metod należących do interfejsu

* Zadanie 4. Zaprojektuj klasy i metody w tych klasach, które reprezentują działanie systemu dziekanatowego
   Hint: Student, Przedmiot, Wykładowca, Ocena, ...
* Zadanie 5. Zaprojektuj klasę, której obiekty reprezentują zbiory elementów typu String
   - Do zbioru można element dodać
   - Ze zbioru można element usunąć
   - Dany element może w zbiorze wystąpić tylko jeden raz
   - Można sprawdzić, czy dany element w zbiorze występuje czy nie
